/*
 * SendX REST API
 * # Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendx.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sendx_java_sdk;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import sendx_java_sdk.LastSentCampaignStat;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import sendx_java_sdk.JSON;

/**
 * DashboardStats
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-25T16:47:38.261598+05:30[Asia/Kolkata]", comments = "Generator version: 7.8.0")
public class DashboardStats {
  public static final String SERIALIZED_NAME_LAST_EMAIL_CAMPAIGN_STAT = "lastEmailCampaignStat";
  @SerializedName(SERIALIZED_NAME_LAST_EMAIL_CAMPAIGN_STAT)
  private LastSentCampaignStat lastEmailCampaignStat;

  public static final String SERIALIZED_NAME_NEWSLETTER_COUNT = "newsletterCount";
  @SerializedName(SERIALIZED_NAME_NEWSLETTER_COUNT)
  private Integer newsletterCount;

  public static final String SERIALIZED_NAME_AUTOMATION_COUNT = "automationCount";
  @SerializedName(SERIALIZED_NAME_AUTOMATION_COUNT)
  private Integer automationCount;

  public DashboardStats() {
  }

  public DashboardStats lastEmailCampaignStat(LastSentCampaignStat lastEmailCampaignStat) {
    this.lastEmailCampaignStat = lastEmailCampaignStat;
    return this;
  }

  /**
   * Get lastEmailCampaignStat
   * @return lastEmailCampaignStat
   */
  @javax.annotation.Nullable
  public LastSentCampaignStat getLastEmailCampaignStat() {
    return lastEmailCampaignStat;
  }

  public void setLastEmailCampaignStat(LastSentCampaignStat lastEmailCampaignStat) {
    this.lastEmailCampaignStat = lastEmailCampaignStat;
  }


  public DashboardStats newsletterCount(Integer newsletterCount) {
    this.newsletterCount = newsletterCount;
    return this;
  }

  /**
   * Number of newsletters sent.
   * @return newsletterCount
   */
  @javax.annotation.Nullable
  public Integer getNewsletterCount() {
    return newsletterCount;
  }

  public void setNewsletterCount(Integer newsletterCount) {
    this.newsletterCount = newsletterCount;
  }


  public DashboardStats automationCount(Integer automationCount) {
    this.automationCount = automationCount;
    return this;
  }

  /**
   * Number of automations set up.
   * @return automationCount
   */
  @javax.annotation.Nullable
  public Integer getAutomationCount() {
    return automationCount;
  }

  public void setAutomationCount(Integer automationCount) {
    this.automationCount = automationCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardStats dashboardStats = (DashboardStats) o;
    return Objects.equals(this.lastEmailCampaignStat, dashboardStats.lastEmailCampaignStat) &&
        Objects.equals(this.newsletterCount, dashboardStats.newsletterCount) &&
        Objects.equals(this.automationCount, dashboardStats.automationCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastEmailCampaignStat, newsletterCount, automationCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardStats {\n");
    sb.append("    lastEmailCampaignStat: ").append(toIndentedString(lastEmailCampaignStat)).append("\n");
    sb.append("    newsletterCount: ").append(toIndentedString(newsletterCount)).append("\n");
    sb.append("    automationCount: ").append(toIndentedString(automationCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("lastEmailCampaignStat");
    openapiFields.add("newsletterCount");
    openapiFields.add("automationCount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DashboardStats
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DashboardStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DashboardStats is not found in the empty JSON string", DashboardStats.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DashboardStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DashboardStats` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `lastEmailCampaignStat`
      if (jsonObj.get("lastEmailCampaignStat") != null && !jsonObj.get("lastEmailCampaignStat").isJsonNull()) {
        LastSentCampaignStat.validateJsonElement(jsonObj.get("lastEmailCampaignStat"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DashboardStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DashboardStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DashboardStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DashboardStats.class));

       return (TypeAdapter<T>) new TypeAdapter<DashboardStats>() {
           @Override
           public void write(JsonWriter out, DashboardStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DashboardStats read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DashboardStats given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DashboardStats
   * @throws IOException if the JSON string is invalid with respect to DashboardStats
   */
  public static DashboardStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DashboardStats.class);
  }

  /**
   * Convert an instance of DashboardStats to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

