/*
 * SendX REST API
 * # Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendx.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sendx_java_sdk;

import sendx_java_sdk.ApiException;
import sendx_java_sdk.CustomEventRequest;
import sendx_java_sdk.EventResponse;
import sendx_java_sdk.RevenueEventRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventApi
 */
@Disabled
public class EventApiTest {

    private final EventApi api = new EventApi();

    /**
     * Record a revenue event for a specific contact
     *
     * Records a revenue event, which can be attributed to campaigns, drips, workflows, or other sources of user interaction.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createRevenueEventTest() throws ApiException {
        RevenueEventRequest revenueEventRequest = null;
        EventResponse response = api.createRevenueEvent(revenueEventRequest);
        // TODO: test validations
    }

    /**
     * Push a custom event associated with a contact
     *
     * Pushes a custom event with properties and values for a specified contact.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pushCustomEventTest() throws ApiException {
        CustomEventRequest customEventRequest = null;
        EventResponse response = api.pushCustomEvent(customEventRequest);
        // TODO: test validations
    }

}
