/*
 * SendX REST API
 * # Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendx.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sendx_java_sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import sendx_java_sdk.CampaignDashboardData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LastSentCampaignStat
 */
public class LastSentCampaignStatTest {
    private final LastSentCampaignStat model = new LastSentCampaignStat();

    /**
     * Model tests for LastSentCampaignStat
     */
    @Test
    public void testLastSentCampaignStat() {
        // TODO: test LastSentCampaignStat
    }

    /**
     * Test the property 'campaign'
     */
    @Test
    public void campaignTest() {
        // TODO: test campaign
    }

    /**
     * Test the property 'sent'
     */
    @Test
    public void sentTest() {
        // TODO: test sent
    }

    /**
     * Test the property 'delivered'
     */
    @Test
    public void deliveredTest() {
        // TODO: test delivered
    }

    /**
     * Test the property 'subscribed'
     */
    @Test
    public void subscribedTest() {
        // TODO: test subscribed
    }

    /**
     * Test the property 'unsubscribed'
     */
    @Test
    public void unsubscribedTest() {
        // TODO: test unsubscribed
    }

    /**
     * Test the property 'open'
     */
    @Test
    public void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'linkClicked'
     */
    @Test
    public void linkClickedTest() {
        // TODO: test linkClicked
    }

    /**
     * Test the property 'replied'
     */
    @Test
    public void repliedTest() {
        // TODO: test replied
    }

}
