/*
 * SendX REST API
 * # Introduction SendX is an email marketing product. It helps you convert website visitors to customers, send them promotional emails, engage with them using drip sequences and craft custom journeys using powerful but simple automations. The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendx.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sendx_java_sdk;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListRequest
 */
public class ListRequestTest {
    private final ListRequest model = new ListRequest();

    /**
     * Model tests for ListRequest
     */
    @Test
    public void testListRequest() {
        // TODO: test ListRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'sendThankYouMail'
     */
    @Test
    public void sendThankYouMailTest() {
        // TODO: test sendThankYouMail
    }

    /**
     * Test the property 'thankYouFromName'
     */
    @Test
    public void thankYouFromNameTest() {
        // TODO: test thankYouFromName
    }

    /**
     * Test the property 'thankYouFromEmail'
     */
    @Test
    public void thankYouFromEmailTest() {
        // TODO: test thankYouFromEmail
    }

    /**
     * Test the property 'thankYouMailSubject'
     */
    @Test
    public void thankYouMailSubjectTest() {
        // TODO: test thankYouMailSubject
    }

    /**
     * Test the property 'thankYouMailMessage'
     */
    @Test
    public void thankYouMailMessageTest() {
        // TODO: test thankYouMailMessage
    }

    /**
     * Test the property 'thankYouSender'
     */
    @Test
    public void thankYouSenderTest() {
        // TODO: test thankYouSender
    }

    /**
     * Test the property 'confirmFromName'
     */
    @Test
    public void confirmFromNameTest() {
        // TODO: test confirmFromName
    }

    /**
     * Test the property 'confirmFromEmail'
     */
    @Test
    public void confirmFromEmailTest() {
        // TODO: test confirmFromEmail
    }

    /**
     * Test the property 'confirmMailSubject'
     */
    @Test
    public void confirmMailSubjectTest() {
        // TODO: test confirmMailSubject
    }

    /**
     * Test the property 'confirmMailMessage'
     */
    @Test
    public void confirmMailMessageTest() {
        // TODO: test confirmMailMessage
    }

    /**
     * Test the property 'confirmSuccessPage'
     */
    @Test
    public void confirmSuccessPageTest() {
        // TODO: test confirmSuccessPage
    }

    /**
     * Test the property 'confirmSender'
     */
    @Test
    public void confirmSenderTest() {
        // TODO: test confirmSender
    }

}
